### ISSUE TITLE
Have theme/demo site avoid relying on minicomp.github.io

### ISSUE THREAD

**Issue by bmschmidt** [minicomp/wax#115]
When I set up a test server to test out Wax, the test site keeps pulling things from the live github site rather than serving them from local sources. So it seems like things are building properly, but in fact they're being served from a mix of localhost:4000 and `minicomp.github.io`. When you click on links in the test site, you get transferred to `minicomp.github.io`. Etc. It's something that's easy to overlook in the address bar, and almost impossible to notice when it's about the location of the IIIF manifests. This is confusing, and makes testing wax installations a bit harder.

Does the minimal computing URL needs to be in `_config.yml`; wouldn't things just work if it's set to `/` or something? 

![image](https://user-images.githubusercontent.com/1110758/117579222-fde7c880-b0bf-11eb-8528-283203682b1d.png)

**Comment by mnyrop** [comment]
@bmschmidt this is a "feature" (aka bug) in Jekyll; I noticed it too: 
- https://github.com/jekyll/jekyll/issues/8541
- https://github.com/jekyll/jekyll/pull/7253

It's super annoying. I haven't had time to figure out which version to roll back to in order to avoid it; might be `4.1` or heaven forbid `< 4.0`. I hope they undo it in `4.3` 🙏🏻  

I'll leave this issue open until there's a clear fix. In the meantime, I'd suggest trying to pin`gem 'jekyll',  '4.1'` in your `Gemfile` or using the CLI options in the Jekyll ticket. 😢

**Comment by bmschmidt** [comment]
In my own site I use `url: ''` instead of `url: 'https://waxsite.benschmidt.org`. This means that all of the links are just relative: `/img/logo.png' instead of `https://waxsite.benschmidt.org/img/logo.png`, etc. Seems to work on localhost and production--would that work for the demo site?
