### ISSUE TITLE
Thumbnails and images not loading

### ISSUE THREAD

**Issue by adamdjbrett** [minicomp/wax#78]
Dear @elotroalex @mnyrop,

Thank you very much for developing such a wonderful resource for digital humanities. I am working to migrate a shockwave flash digital humanities site to a more modern stack and so I decided to use Jekyll and the wonderful wax template. I know there is a lot going on presently in this time of COVID-19 but I have a question about wax. 
I'm running
- ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
- jekyll 4.0.0
- wax:derivatives:iiif

I am having two issues:
1. on pages calling: collection_gallery.html I am unable to load the thumbnail gallery. However I'm not getting an error message in terminal or in Google Chrome Dev Tools.
2. when I go to my collection `_qatar` some objects load in `openseadragon` and others do not.

my repository is: [github.com/adamdjbrett/sullivan-clinton-wax](https://github.com/adamdjbrett/sullivan-clinton-wax)

I feel like I am missing something obvious what should I do?

**Comment by mnyrop** [comment]
Hi @adamdjbrett. After just a quick glance, my guess is it's not working because your images are too small (e.g., https://github.com/adamdjbrett/sullivan-clinton-wax/blob/master/_data/raw_images/visual-gallery/obj109.jpg).

Wax creates derivative images to use for thumbnails and for IIIF tiles. If it cannot "slice" a thumbnail because the thumbnail size is greater than the original image, it will skip along. 

I should have some time later today/early next week to poke around more thoroughly if helpful, though it might be worth using the simple image derivatives task (versus `wax:derivatives:iiif`) just to test and see how the images show up. (This should help on the item pages, not necessarily on the gallery.)

Hope this is helpful. More to come.
–Marii

**Comment by adamdjbrett** [comment]
@mnyrop thank you so much for taking a look and your help. It took me a minute to figure that need to  theme layout from image_viewer:`openseadragon` to `simple_image_viewer`.  Once I did that the simple image derivates tasks seems to be working and will work well for my purposes. I am having a couple of issues with the simple viewer.
- does the simple viewer not handle folders (thats ok I don't need a folder)
- how do I keep the simple viewer from stretching small images? I'm working to try and replace as many as possible with higher resolution images.
- What should I do with my two panorama images `obj74` and `obj77` should I make a proper ratio and then in the metadata block have a link to the full size?
- On index.md and `collection.md` what would be the best way to display the simply image gallery and have a rudimentary image sort?

Thank you for all of your help and assistance. You have been most helpful.

Warm Regards,
-Adam

**Comment by mnyrop** [comment]
@adamdjbrett a million years late, but this issue is now fixed. if you want to patch it in any existing wax sites, just replace your content in `_includes/osd_iiif_image_viewer.html` with the updated version that grabs thumbnails explicitly from the IIIF manifest:

https://github.com/minicomp/wax/blob/main/_includes/osd_iiif_image_viewer.html

**Comment by adamdjbrett** [comment]
Thank you very much I really appreciate
