### ISSUE TITLE
Multi-page items displaying in random page order

### ISSUE THREAD

**Issue by ansleyerickson** [minicomp/wax#83]
Hello, 
All of the multi-image items on my attempted Wax site are displaying in a random order. The raw image files are ordered numerically, but don't appear in that order via openseadragon. This is happening with items that are jpegs and items that are tiffs. Any suggestions on places to start? 
Thank you. 
Ansley

**Comment by mnyrop** [comment]
Hi @ansleyerickson, you're 100% correct on this issue. @pbinkley submitted [a fix](https://github.com/minicomp/wax_tasks/pull/47) recently, so I should have a new release for you soon that preserves the order.

I'll leave this ticket open and let you know when a new release is available + how to update it in your wax instance.

**Comment by ansleyerickson** [comment]
Great news! Thank you!

**Comment by mnyrop** [comment]
Hi @ansleyerickson, this has been fixed in the newest released `wax_tasks`.
To update your project, open the `wax_theme.gemspec` file in your project and replace the contents of the file with the new version, available here: https://github.com/minicomp/wax/blob/main/wax_theme.gemspec.

Then run `bundle install` in the terminal within your project folder to update the dependencies, and regenerate the image derivatives/pages as needed.

Let me know if you have any questions!
